import type { Metadata } from "next";
import { doctor, siteUrl } from "@/lib/data";

/**
 * Canonical/OG helpers for the HAND-BUILT routes only.
 *
 * The 197 migrated routes do NOT come through here: their canonical, title, description
 * and og:* values are replayed verbatim from the WordPress capture by metadataFromDoc()
 * in lib/content.ts, and that parity is deliberate — those URLs are already indexed with
 * exactly those values. This module exists for the four routes that have no capture
 * behind them (/appointment/, /conditions/, /testimonials/, /contact-us/), which
 * previously emitted no canonical at all and inherited the root layout's og: block,
 * so all four announced `og:url = https://drjayeshsardhara.com/` — the homepage.
 */

/**
 * The site-wide social card, generated by scripts/build-og-image.mjs.
 *
 * One shared image rather than a per-page one: the WordPress capture carries no og:image
 * for any of the 203 URLs, so there is nothing per-page to preserve, and a single card
 * that names the doctor is more useful in a WhatsApp or LinkedIn preview than a blog
 * post's inline illustration would be. `metadataBase` in app/layout.tsx resolves the
 * relative path to the production domain.
 *
 * Applied to indexable pages only — a noindex archive has no reason to carry one.
 */
export const OG_IMAGE = {
  url: "/og-image.png",
  width: 1200,
  height: 630,
  alt: `${doctor.name} — ${doctor.title}`,
} as const;

/**
 * Normalize a site-relative path to the single production URL Google should see.
 *
 * `trailingSlash: true` in next.config.ts, so every route is served WITH a trailing
 * slash and every canonical must carry one — a canonical without it points at a URL
 * that 308s, which wastes the signal.
 *
 * Query strings and fragments are stripped: none of the routes here take a parameter
 * that changes the page, so `?utm_source=…`, `?fbclid=…` and friends are all the same
 * document and must canonicalize to the bare path.
 *
 * Case is left alone on purpose. Every route in this project is already lower-case, and
 * blindly lower-casing would silently corrupt the canonical of any future slug that
 * isn't — a wrong canonical is worse than an unnormalized one.
 */
export function canonicalUrl(pathname: string): string {
  const path = `/${pathname}`
    .split("?")[0]
    .split("#")[0]
    .replace(/\/+/g, "/");
  return `${siteUrl}${path.endsWith("/") ? path : `${path}/`}`;
}

/**
 * Metadata for a hand-built route: self-referencing canonical plus an og:/twitter: block
 * that describes THIS page rather than inheriting the homepage's.
 *
 * `title` is the bare page title — the root layout's `%s · Dr. Jayesh Sardhara` template
 * expands it for <title>, so og:title is built to match what the template produces.
 */
export function pageMetadata({
  path,
  title,
  description,
}: {
  path: string;
  title: string;
  description: string;
}): Metadata {
  const url = canonicalUrl(path);
  const fullTitle = `${title} · ${doctor.name}`;

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      url,
      title: fullTitle,
      description,
      siteName: doctor.name,
      locale: "en_US",
      images: [OG_IMAGE],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [OG_IMAGE.url] },
  };
}
