import { contentProfileSchema, generatedBlogSchema, topicCandidatesSchema } from "./schemas";
import type {
  AIProvider,
  BlogPlan,
  BlogRequest,
  CombinedReview,
  ContentProfile,
  CorpusItem,
  GeneratedBlog,
  ProviderInfo,
  TopicCandidate,
  TopicRequest,
} from "./types";

export class MockAIProvider implements AIProvider {
  readonly info: ProviderInfo = { provider: "mock", model: "mock-1" };

  async analyseBlogs(items: CorpusItem[]): Promise<ContentProfile> {
    const categories = [...new Set(items.flatMap((i) => i.categories))].filter(Boolean);
    const words = items.length
      ? Math.round(items.reduce((sum, i) => sum + i.wordCount, 0) / items.length)
      : 900;

    const shape = contentProfileSchema.parse({
      writingStyle: {
        tone: "Calm and factual; explains before it reassures.",
        vocabulary: "Plain English, with each clinical term defined on first use.",
        sentenceStructure: "Short declarative sentences; few subordinate clauses.",
        paragraphStructure: "Two to four sentences per paragraph.",
        introductionStyle: "Names the symptom or question the reader arrived with.",
        conclusionStyle: "Summarises, then says when to see a doctor.",
        headingPatterns: "Question-shaped H2s in the reader's own words.",
        faqStyle: "Four to six questions, each answered in two or three sentences.",
        ctaStyle: "One line inviting a consultation, no urgency language.",
        medicalTerminology: "Used, then immediately translated.",
        patientFriendlyLanguage: "Second person, no hedging stacks.",
        typicalWordCount: Math.max(300, Math.min(4000, words)),
      },
      topicIntelligence: {
        clusters: categories.slice(0, 4).map((name) => ({
          name,
          topics: items.filter((i) => i.categories.includes(name)).slice(0, 5).map((i) => i.title),
        })),
        coveredTopics: items.slice(0, 40).map((i) => i.title),
        contentGaps: ["Recovery timelines after endoscopic spine surgery", "When back pain is an emergency"],
        topicsToAvoid: items.slice(0, 5).map((i) => i.title),
        recentTopics: items
          .filter((i) => i.publishedAt)
          .sort((a, b) => (b.publishedAt ?? "").localeCompare(a.publishedAt ?? ""))
          .slice(0, 10)
          .map((i) => i.title),
      },
      seoPatterns: {
        titlePatterns: ["<Condition>: Symptoms, Causes and Treatment", "What Is <Procedure>?"],
        metaDescriptionPatterns: ["Opens with the condition, closes with a consultation line."],
        keywordUsage: "Focus keyword in the title, the first paragraph and one H2.",
        slugPatterns: "Lowercase, hyphenated, condition first, no dates.",
        headingStructure: "H2 sections, H3 only inside long sections.",
        internalLinking: "Two to four links to related condition pages.",
      },
      imagePatterns: {
        style: "Clinical photography over illustration.",
        composition: "Single subject, generous negative space on the right.",
        subject: "Anatomy, clinical settings, consultations.",
        realism: "Photorealistic; no stylised anatomy.",
        aspectRatio: "16:9",
        textPolicy: "No text baked into images.",
        featuredImageStyle: "Wide clinical photograph, cool neutral tones.",
      },
    });

    return {
      ...shape,
      stats: {
        markdownPosts: items.filter((i) => i.source === "markdown").length,
        supabasePosts: items.filter((i) => i.source === "supabase").length,
        analysedAt: new Date().toISOString(),
      },
    };
  }

  async generateTopicCandidates(request: TopicRequest): Promise<TopicCandidate[]> {
    const intents = ["informational", "symptom", "treatment", "comparison"] as const;
    const gaps = request.profile?.topicIntelligence.contentGaps ?? [];

    const { candidates } = topicCandidatesSchema.parse({
      candidates: Array.from({ length: Math.max(1, request.count) }, (_, i) => ({
        topic: gaps[i] ?? `Mock topic ${i + 1} for ${request.categories[0] ?? "spine"}`,
        focusKeyword: `mock keyword ${i + 1}`,
        secondaryKeywords: [`mock secondary ${i + 1}a`, `mock secondary ${i + 1}b`],
        intent: intents[i % intents.length],
        contentGap: gaps[i] ?? "Not covered by any existing article.",
        reason: "Generated by MockAIProvider; no model was called.",
        aiEstimate: 90 - i * 3,
        category: request.categories[i % Math.max(1, request.categories.length)] ?? "",
      })),
    });
    return candidates;
  }

  async generateBlogPlan(request: BlogRequest): Promise<BlogPlan> {
    return {
      searchIntent: "informational",
      angle: `Mock plan for "${request.topic}". No model was called.`,
      focusKeyword: request.focusKeyword || "mock keyword",
      secondaryKeywords: request.secondaryKeywords.slice(0, 5),
      outline: [
        { heading: "What it is", summary: "Define the condition in plain language." },
        { heading: "Why it happens", summary: "Common causes." },
        { heading: "When to see a doctor", summary: "Red flags." },
      ],
      faqPlan: request.settings.includeFaq ? ["Is this serious?", "How long does it last?"] : [],
      ctaPlan: request.settings.includeCta ? "Invite a consultation." : "",
      imageConcepts: request.settings.includeImageSuggestions ? ["Clinical setting, wide"] : [],
      seoStrategy: "Keyword in the title, the opening line and one H2.",
      category: request.category,
    };
  }

  async generateCompleteBlog(request: BlogRequest, plan: BlogPlan | null): Promise<GeneratedBlog> {
    const slug =
      request.topic
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")
        .slice(0, 60) || "mock-post";

    const headings = plan?.outline.length
      ? plan.outline
      : [
          { heading: "What it is", summary: "" },
          { heading: "Why it happens", summary: "" },
          { heading: "When to see a doctor", summary: "" },
        ];

    return generatedBlogSchema.parse({
      title: request.topic,
      slug,
      excerpt: `Mock excerpt for "${request.topic}". Generated without calling a model.`,
      contentMarkdown: [
        "> This article was produced by MockAIProvider. No model was called and nothing here is medical content.",
        "",
        ...headings.flatMap((h) => [`## ${h.heading}`, "", `Placeholder body for ${h.heading.toLowerCase()}.`, ""]),
      ].join("\n"),
      primaryKeyword: plan?.focusKeyword || request.focusKeyword || "mock keyword",
      secondaryKeywords: (plan?.secondaryKeywords ?? request.secondaryKeywords).slice(0, 5),
      metaTitle: request.topic.slice(0, 60),
      metaDescription: `Mock meta description for ${request.topic}. Replace before publishing.`.slice(0, 160),
      faq: request.settings.includeFaq
        ? [{ question: "Is this a real article?", answer: "No. It came from the mock provider." }]
        : [],
      cta: request.settings.includeCta ? "Book a consultation to discuss your symptoms." : "",
      category: plan?.category || request.category,
      tags: ["mock"],
      imageSuggestions: request.settings.includeImageSuggestions
        ? [
            {
              role: "featured",
              concept: plan?.imageConcepts[0] ?? "Mock featured image concept",
              subject: "Clinical setting",
              setting: "Consulting room",
              composition: "Single subject, space at right",
              lighting: "Soft daylight",
              visualStyle: "Photorealistic",
              aspectRatio: "16:9",
              includeText: false,
              prompt: `Photorealistic clinical photograph illustrating ${request.topic}, 16:9, no text.`,
              altText: `Illustration for ${request.topic}`,
              placement: "Top of article",
            },
          ]
        : [],
      internalLinkSuggestions: request.references.slice(0, 3).map((r) => r.title),
      externalSourceSuggestions: [],
    });
  }

  async reviewCompleteBlog(): Promise<CombinedReview> {
    return {
      clean: true,
      medical: [],
      originality: [],
      style: [],
      grammar: [],
      language: [],
      sources: [],
    };
  }
}
